### ISSUE TITLE
거대언어모델 응답 vs 모범 응답 유사도 검사

### ISSUE THREAD

**Issue by effort-type** [915-Lab/DeuChatbot#29]
## 📝 Description
질의에 따른 거대언어모델의 응답과 해당 질의의 모범 답안을 코사인 유사도 검사하여 수치를 기록하기

## 📍 Todo
- [x] 질의와 모범 응답을 엑셀 파일에서 가져오기
- [x] 질의에 따른 거대언어모델 응답과 모범 응답을 코사인 유사도 검사하기
- [x] 코사인 유사도 검사 결과를 엑셀 파일로 저장하기
