### ISSUE TITLE
거대언어모델을 통한 질의응답 데이터셋 생성

### ISSUE THREAD

**Issue by effort-type** [915-Lab/DeuChatbot#34]
## 📝 Description
24.06.13일 기준 가장 성능이 우수한 GPT-4o 모델을 통해 질의응답 데이터셋을 생성하고자 한다.

## 📍 Todo
- [x] 적합한 프롬프트 생성
- [x] RAG 시스템 구축
- [x] 예시 3~5개 정도 입력
- [x] jsonl 파일로 저장
- [x] 생성된 데이터셋 검증
- [x] 생성된 데이터셋 HuggingFace 업로드
