### ISSUE TITLE
실험 자동화 구현

### ISSUE THREAD

**Issue by effort-type** [915-Lab/DeuChatbot#37]
## 📝 Description
다양한 실험 전략에 따른 실험을 진행할 때 편리하도록 소스 코드 변경하기

## 📍 Todo
- [x] 임베딩 모델을 세부적으로 선택할 수 있도록 하기
- [x] 파일 이름을 임베딩 모델, 청크 사이즈, 오버랩 사이즈에 알맞게 변경되도록 하기
- [x] RecursiveCharacterTextSplitter 문서 분할기 변경 (토크나이저 gpt-4o에서 사용하는 o200k_base 사용)
- [x] 청크 사이즈, 오버랩 사이즈 조절 실험 편리하게 하도록 사이즈 입력받도록 진행
